[2025-10-15T19:54:53.780+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-15T19:54:53.790+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.dbt_run manual__2025-10-15T19:54:04.511283+00:00 [queued]>
[2025-10-15T19:54:53.793+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.dbt_run manual__2025-10-15T19:54:04.511283+00:00 [queued]>
[2025-10-15T19:54:53.794+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-15T19:54:53.798+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-15 19:54:04.511283+00:00
[2025-10-15T19:54:53.800+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-15T19:54:53.801+0000] {standard_task_runner.py:64} INFO - Started process 83 to run task
[2025-10-15T19:54:53.801+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'game_sentiment_data_pipeline', 'dbt_run', 'manual__2025-10-15T19:54:04.511283+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpryrwogtq']
[2025-10-15T19:54:53.802+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask dbt_run
[2025-10-15T19:54:53.819+0000] {task_command.py:426} INFO - Running <TaskInstance: game_sentiment_data_pipeline.dbt_run manual__2025-10-15T19:54:04.511283+00:00 [running]> on host e37ef65f9b61
[2025-10-15T19:54:53.851+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='game_sentiment_data_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-15T19:54:04.511283+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-15T19:54:04.511283+00:00'
[2025-10-15T19:54:53.851+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-15T19:54:53.857+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-15T19:54:53.858+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/silver_layer && dbt run']
[2025-10-15T19:54:53.862+0000] {subprocess.py:86} INFO - Output:
[2025-10-15T19:54:53.863+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-10-15T19:54:53.863+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-10-15T19:54:53.864+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-15T19:54:53.868+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-10-15T19:54:53.870+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=game_sentiment_data_pipeline, task_id=dbt_run, run_id=manual__2025-10-15T19:54:04.511283+00:00, execution_date=20251015T195404, start_date=20251015T195453, end_date=20251015T195453
[2025-10-15T19:54:53.875+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 72 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 83)
[2025-10-15T19:54:53.902+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-15T19:54:53.912+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-15T19:54:53.914+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
