[2025-10-21T19:17:37.515+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-21T19:17:37.525+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.DT manual__2025-10-21T19:15:52.651602+00:00 [queued]>
[2025-10-21T19:17:37.527+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.DT manual__2025-10-21T19:15:52.651602+00:00 [queued]>
[2025-10-21T19:17:37.528+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-21T19:17:37.532+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): DT> on 2025-10-21 19:15:52.651602+00:00
[2025-10-21T19:17:37.534+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=339) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-21T19:17:37.535+0000] {standard_task_runner.py:64} INFO - Started process 340 to run task
[2025-10-21T19:17:37.535+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'game_sentiment_data_pipeline', 'DT', 'manual__2025-10-21T19:15:52.651602+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmp6j9z1dad']
[2025-10-21T19:17:37.536+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask DT
[2025-10-21T19:17:37.551+0000] {task_command.py:426} INFO - Running <TaskInstance: game_sentiment_data_pipeline.DT manual__2025-10-21T19:15:52.651602+00:00 [running]> on host 853ab210954c
[2025-10-21T19:17:37.579+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='game_sentiment_data_pipeline' AIRFLOW_CTX_TASK_ID='DT' AIRFLOW_CTX_EXECUTION_DATE='2025-10-21T19:15:52.651602+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-21T19:15:52.651602+00:00'
[2025-10-21T19:17:37.579+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-21T19:17:37.584+0000] {logging_mixin.py:188} INFO - Invoking Lambda function: DataTransfer
[2025-10-21T19:17:41.318+0000] {logging_mixin.py:188} INFO - Lambda response: {'ResponseMetadata': {'RequestId': '5419efec-fd02-4f6e-8077-ac46e4908ac4', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 21 Oct 2025 19:17:41 GMT', 'content-type': 'application/json', 'content-length': '1316', 'connection': 'keep-alive', 'x-amzn-requestid': '5419efec-fd02-4f6e-8077-ac46e4908ac4', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'Root=1-68f7dc51-23bcf84a3e7d6d1c678409fb;Parent=436ac42d6611599e;Sampled=0;Lineage=1:6ca1d8aa:0'}, 'RetryAttempts': 0}, 'StatusCode': 200, 'FunctionError': 'Unhandled', 'ExecutedVersion': '$LATEST', 'Payload': <botocore.response.StreamingBody object at 0xffff9e355060>}
[2025-10-21T19:17:41.319+0000] {logging_mixin.py:188} INFO - Lambda output: {"errorMessage": "vgsa/gold/sentiment_analysis_result/sentiment.parquet", "errorType": "FileNotFoundError", "requestId": "5419efec-fd02-4f6e-8077-ac46e4908ac4", "stackTrace": ["  File \"/var/task/trans.py\", line 14, in handler\n    df_file1 = pd.read_parquet(file1)\n", "  File \"/var/lang/lib/python3.12/site-packages/pandas/io/parquet.py\", line 669, in read_parquet\n    return impl.read(\n", "  File \"/var/lang/lib/python3.12/site-packages/pandas/io/parquet.py\", line 265, in read\n    pa_table = self.api.parquet.read_table(\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/parquet/core.py\", line 1843, in read_table\n    dataset = ParquetDataset(\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/parquet/core.py\", line 1424, in __init__\n    self._dataset = ds.dataset(path_or_paths, filesystem=filesystem,\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 790, in dataset\n    return _filesystem_dataset(source, **kwargs)\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 472, in _filesystem_dataset\n    fs, paths_or_selector = _ensure_single_source(source, filesystem)\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 437, in _ensure_single_source\n    raise FileNotFoundError(path)\n"]}
[2025-10-21T19:17:41.320+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-21T19:17:41.320+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-21T19:17:41.325+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=game_sentiment_data_pipeline, task_id=DT, run_id=manual__2025-10-21T19:15:52.651602+00:00, execution_date=20251021T191552, start_date=20251021T191737, end_date=20251021T191741
[2025-10-21T19:17:41.373+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-21T19:17:41.382+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-21T19:17:41.383+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
