[2025-10-15T19:50:41.302+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-15T19:50:41.312+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.dbt_run manual__2025-10-15T19:49:41.602939+00:00 [queued]>
[2025-10-15T19:50:41.315+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.dbt_run manual__2025-10-15T19:49:41.602939+00:00 [queued]>
[2025-10-15T19:50:41.315+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-15T19:50:41.320+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-15 19:49:41.602939+00:00
[2025-10-15T19:50:41.322+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-15T19:50:41.323+0000] {standard_task_runner.py:64} INFO - Started process 81 to run task
[2025-10-15T19:50:41.323+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'game_sentiment_data_pipeline', 'dbt_run', 'manual__2025-10-15T19:49:41.602939+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpol8c5ioj']
[2025-10-15T19:50:41.324+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask dbt_run
[2025-10-15T19:50:41.341+0000] {task_command.py:426} INFO - Running <TaskInstance: game_sentiment_data_pipeline.dbt_run manual__2025-10-15T19:49:41.602939+00:00 [running]> on host 7c297b2e9a6b
[2025-10-15T19:50:41.369+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='game_sentiment_data_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-15T19:49:41.602939+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-15T19:49:41.602939+00:00'
[2025-10-15T19:50:41.370+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-15T19:50:41.375+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-15T19:50:41.375+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/silver_layer && dbt run']
[2025-10-15T19:50:41.379+0000] {subprocess.py:86} INFO - Output:
[2025-10-15T19:50:41.380+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-10-15T19:50:41.380+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-10-15T19:50:41.380+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-15T19:50:41.384+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-10-15T19:50:41.386+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=game_sentiment_data_pipeline, task_id=dbt_run, run_id=manual__2025-10-15T19:49:41.602939+00:00, execution_date=20251015T194941, start_date=20251015T195041, end_date=20251015T195041
[2025-10-15T19:50:41.390+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 67 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 81)
[2025-10-15T19:50:41.424+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-15T19:50:41.432+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-15T19:50:41.434+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
