[2025-10-21T19:21:24.545+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-21T19:21:24.555+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.DT manual__2025-10-21T19:19:47.378874+00:00 [queued]>
[2025-10-21T19:21:24.558+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.DT manual__2025-10-21T19:19:47.378874+00:00 [queued]>
[2025-10-21T19:21:24.558+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-21T19:21:24.563+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): DT> on 2025-10-21 19:19:47.378874+00:00
[2025-10-21T19:21:24.566+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=447) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-21T19:21:24.566+0000] {standard_task_runner.py:64} INFO - Started process 448 to run task
[2025-10-21T19:21:24.567+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'game_sentiment_data_pipeline', 'DT', 'manual__2025-10-21T19:19:47.378874+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmp8dewks3p']
[2025-10-21T19:21:24.567+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask DT
[2025-10-21T19:21:24.585+0000] {task_command.py:426} INFO - Running <TaskInstance: game_sentiment_data_pipeline.DT manual__2025-10-21T19:19:47.378874+00:00 [running]> on host 853ab210954c
[2025-10-21T19:21:24.619+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='game_sentiment_data_pipeline' AIRFLOW_CTX_TASK_ID='DT' AIRFLOW_CTX_EXECUTION_DATE='2025-10-21T19:19:47.378874+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-21T19:19:47.378874+00:00'
[2025-10-21T19:21:24.619+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-21T19:21:24.625+0000] {logging_mixin.py:188} INFO - Invoking Lambda function: DataTransfer
[2025-10-21T19:21:24.855+0000] {logging_mixin.py:188} INFO - Lambda response: {'ResponseMetadata': {'RequestId': 'c5c7cd37-d121-410d-be2e-09abdfc33e90', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 21 Oct 2025 19:21:24 GMT', 'content-type': 'application/json', 'content-length': '1316', 'connection': 'keep-alive', 'x-amzn-requestid': 'c5c7cd37-d121-410d-be2e-09abdfc33e90', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'Root=1-68f7dd34-55c2aecb23260229450c4b40;Parent=0ccedf71e0c93133;Sampled=0;Lineage=1:6ca1d8aa:0'}, 'RetryAttempts': 0}, 'StatusCode': 200, 'FunctionError': 'Unhandled', 'ExecutedVersion': '$LATEST', 'Payload': <botocore.response.StreamingBody object at 0xffff9e359840>}
[2025-10-21T19:21:24.856+0000] {logging_mixin.py:188} INFO - Lambda output: {"errorMessage": "vgsa/gold/sentiment_analysis_result/sentiment.parquet", "errorType": "FileNotFoundError", "requestId": "c5c7cd37-d121-410d-be2e-09abdfc33e90", "stackTrace": ["  File \"/var/task/trans.py\", line 14, in handler\n    df_file1 = pd.read_parquet(file1)\n", "  File \"/var/lang/lib/python3.12/site-packages/pandas/io/parquet.py\", line 669, in read_parquet\n    return impl.read(\n", "  File \"/var/lang/lib/python3.12/site-packages/pandas/io/parquet.py\", line 265, in read\n    pa_table = self.api.parquet.read_table(\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/parquet/core.py\", line 1843, in read_table\n    dataset = ParquetDataset(\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/parquet/core.py\", line 1424, in __init__\n    self._dataset = ds.dataset(path_or_paths, filesystem=filesystem,\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 790, in dataset\n    return _filesystem_dataset(source, **kwargs)\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 472, in _filesystem_dataset\n    fs, paths_or_selector = _ensure_single_source(source, filesystem)\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 437, in _ensure_single_source\n    raise FileNotFoundError(path)\n"]}
[2025-10-21T19:21:24.857+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-21T19:21:24.857+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-21T19:21:24.866+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=game_sentiment_data_pipeline, task_id=DT, run_id=manual__2025-10-21T19:19:47.378874+00:00, execution_date=20251021T191947, start_date=20251021T192124, end_date=20251021T192124
[2025-10-21T19:21:24.882+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-21T19:21:24.889+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-21T19:21:24.890+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
