[2025-10-15T20:07:37.261+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-15T20:07:37.293+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.DT manual__2025-10-15T20:06:20.480413+00:00 [queued]>
[2025-10-15T20:07:37.306+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.DT manual__2025-10-15T20:06:20.480413+00:00 [queued]>
[2025-10-15T20:07:37.307+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-15T20:07:37.323+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): DT> on 2025-10-15 20:06:20.480413+00:00
[2025-10-15T20:07:37.328+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=289) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-15T20:07:37.331+0000] {standard_task_runner.py:64} INFO - Started process 290 to run task
[2025-10-15T20:07:37.332+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'game_sentiment_data_pipeline', 'DT', 'manual__2025-10-15T20:06:20.480413+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpfzfmdui3']
[2025-10-15T20:07:37.334+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask DT
[2025-10-15T20:07:37.379+0000] {task_command.py:426} INFO - Running <TaskInstance: game_sentiment_data_pipeline.DT manual__2025-10-15T20:06:20.480413+00:00 [running]> on host e37ef65f9b61
[2025-10-15T20:07:37.450+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='game_sentiment_data_pipeline' AIRFLOW_CTX_TASK_ID='DT' AIRFLOW_CTX_EXECUTION_DATE='2025-10-15T20:06:20.480413+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-15T20:06:20.480413+00:00'
[2025-10-15T20:07:37.451+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-15T20:07:37.462+0000] {logging_mixin.py:188} INFO - Invoking Lambda function: DataTransfer
[2025-10-15T20:07:40.970+0000] {logging_mixin.py:188} INFO - Lambda response: {'ResponseMetadata': {'RequestId': 'd090c9fc-d3b9-42ce-a51a-b5e1c8cdcaa8', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Wed, 15 Oct 2025 20:07:40 GMT', 'content-type': 'application/json', 'content-length': '1389', 'connection': 'keep-alive', 'x-amzn-requestid': 'd090c9fc-d3b9-42ce-a51a-b5e1c8cdcaa8', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'Root=1-68efff09-77d9726d64d6e8562ee6d545;Parent=4721d1213bff2e04;Sampled=0;Lineage=1:6ca1d8aa:0'}, 'RetryAttempts': 0}, 'StatusCode': 200, 'FunctionError': 'Unhandled', 'ExecutedVersion': '$LATEST', 'Payload': <botocore.response.StreamingBody object at 0xffff925fcdf0>}
[2025-10-15T20:07:40.971+0000] {logging_mixin.py:188} INFO - Lambda output: {"errorMessage": "vgsa/silver/silver_tables_dbt_result/games_sentiment_analysis_silver/game_reviews_summary/e7056eb7-6278-4cb5-9ca7-613cd3cd98bc", "errorType": "FileNotFoundError", "requestId": "d090c9fc-d3b9-42ce-a51a-b5e1c8cdcaa8", "stackTrace": ["  File \"/var/task/trans.py\", line 15, in handler\n    df_file2 = pd.read_parquet(file2)\n", "  File \"/var/lang/lib/python3.12/site-packages/pandas/io/parquet.py\", line 669, in read_parquet\n    return impl.read(\n", "  File \"/var/lang/lib/python3.12/site-packages/pandas/io/parquet.py\", line 265, in read\n    pa_table = self.api.parquet.read_table(\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/parquet/core.py\", line 1843, in read_table\n    dataset = ParquetDataset(\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/parquet/core.py\", line 1424, in __init__\n    self._dataset = ds.dataset(path_or_paths, filesystem=filesystem,\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 790, in dataset\n    return _filesystem_dataset(source, **kwargs)\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 472, in _filesystem_dataset\n    fs, paths_or_selector = _ensure_single_source(source, filesystem)\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 437, in _ensure_single_source\n    raise FileNotFoundError(path)\n"]}
[2025-10-15T20:07:40.971+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-15T20:07:40.972+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-15T20:07:40.981+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=game_sentiment_data_pipeline, task_id=DT, run_id=manual__2025-10-15T20:06:20.480413+00:00, execution_date=20251015T200620, start_date=20251015T200737, end_date=20251015T200740
[2025-10-15T20:07:40.997+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-15T20:07:41.005+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-15T20:07:41.006+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
