[2025-10-21T19:58:19.842+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-21T19:58:19.853+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.sent_analysis manual__2025-10-21T19:56:45.517434+00:00 [queued]>
[2025-10-21T19:58:19.856+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: game_sentiment_data_pipeline.sent_analysis manual__2025-10-21T19:56:45.517434+00:00 [queued]>
[2025-10-21T19:58:19.856+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-21T19:58:19.860+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): sent_analysis> on 2025-10-21 19:56:45.517434+00:00
[2025-10-21T19:58:19.863+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=990) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-21T19:58:19.863+0000] {standard_task_runner.py:64} INFO - Started process 991 to run task
[2025-10-21T19:58:19.864+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'game_sentiment_data_pipeline', 'sent_analysis', 'manual__2025-10-21T19:56:45.517434+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmp0vw0_yew']
[2025-10-21T19:58:19.864+0000] {standard_task_runner.py:91} INFO - Job 104: Subtask sent_analysis
[2025-10-21T19:58:19.880+0000] {task_command.py:426} INFO - Running <TaskInstance: game_sentiment_data_pipeline.sent_analysis manual__2025-10-21T19:56:45.517434+00:00 [running]> on host 853ab210954c
[2025-10-21T19:58:19.909+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='game_sentiment_data_pipeline' AIRFLOW_CTX_TASK_ID='sent_analysis' AIRFLOW_CTX_EXECUTION_DATE='2025-10-21T19:56:45.517434+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-21T19:56:45.517434+00:00'
[2025-10-21T19:58:19.909+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-21T19:58:19.915+0000] {logging_mixin.py:188} INFO - Invoking Lambda function: sentiment_ntbk
[2025-10-21T19:58:46.249+0000] {logging_mixin.py:188} INFO - Lambda response: {'ResponseMetadata': {'RequestId': 'c093bc21-1e95-487c-919d-829c96b641a0', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 21 Oct 2025 19:58:46 GMT', 'content-type': 'application/json', 'content-length': '1640', 'connection': 'keep-alive', 'x-amzn-requestid': 'c093bc21-1e95-487c-919d-829c96b641a0', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'Root=1-68f7e5db-154fbfd37dbfa0d00b3d8d54;Parent=1bbeffbd54780496;Sampled=0;Lineage=1:235f6cb5:0'}, 'RetryAttempts': 0}, 'StatusCode': 200, 'FunctionError': 'Unhandled', 'ExecutedVersion': '$LATEST', 'Payload': <botocore.response.StreamingBody object at 0xffff9e67e440>}
[2025-10-21T19:58:46.250+0000] {logging_mixin.py:188} INFO - Lambda output: {"errorMessage": "GetFileInfo() yielded path 'vgsa/silver/silver_tables_dbt_result/game_reviews/20251021_195800_00015_ypn2e_ff6238bb-b4fb-43fa-8dcb-d8c5229ef0cc', which is outside base dir 's3://vgsa/silver/silver_tables_dbt_result/game_reviews/'", "errorType": "ArrowInvalid", "requestId": "c093bc21-1e95-487c-919d-829c96b641a0", "stackTrace": ["  File \"/var/task/sentiment_analysis.py\", line 14, in handler\n    df = pd.read_parquet(file_path,filesystem=fs)\n", "  File \"/var/lang/lib/python3.12/site-packages/pandas/io/parquet.py\", line 669, in read_parquet\n    return impl.read(\n", "  File \"/var/lang/lib/python3.12/site-packages/pandas/io/parquet.py\", line 265, in read\n    pa_table = self.api.parquet.read_table(\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/parquet/core.py\", line 1843, in read_table\n    dataset = ParquetDataset(\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/parquet/core.py\", line 1424, in __init__\n    self._dataset = ds.dataset(path_or_paths, filesystem=filesystem,\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 790, in dataset\n    return _filesystem_dataset(source, **kwargs)\n", "  File \"/var/lang/lib/python3.12/site-packages/pyarrow/dataset.py\", line 480, in _filesystem_dataset\n    factory = FileSystemDatasetFactory(fs, paths_or_selector, format, options)\n", "  File \"pyarrow/_dataset.pyx\", line 3388, in pyarrow._dataset.FileSystemDatasetFactory.__init__\n", "  File \"pyarrow/error.pxi\", line 155, in pyarrow.lib.pyarrow_internal_check_status\n", "  File \"pyarrow/error.pxi\", line 92, in pyarrow.lib.check_status\n"]}
[2025-10-21T19:58:46.251+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-21T19:58:46.252+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-21T19:58:46.263+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=game_sentiment_data_pipeline, task_id=sent_analysis, run_id=manual__2025-10-21T19:56:45.517434+00:00, execution_date=20251021T195645, start_date=20251021T195819, end_date=20251021T195846
[2025-10-21T19:58:46.288+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-21T19:58:46.297+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-21T19:58:46.298+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
